name: uber_health_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to 
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  lottie: ^3.3.1
  http: ^1.3.0
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  firebase_auth: ^5.5.1
  cloud_functions: ^5.0.0
  flutter_webrtc: ^0.12.11
  connectivity_plus: ^6.1.3
  intl: ^0.20.2
  agora_rtc_engine: ^6.5.1
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/images/welcome.png
    - assets/images/cough_cold.png
    - assets/images/uti.png
    - assets/images/allergies.png
    - assets/images/gi.png
    - assets/images/skin.png
    - assets/images/msk.png
    - assets/images/general.png
    - assets/images/other.png
    - assets/images/neck.png
    - assets/images/back.png
    - assets/images/shoulder.png
    - assets/images/elbow.png
    - assets/images/wrist.png
    - assets/images/hip.png
    - assets/images/knee.png
    - assets/images/foot.png

flutter_native_splash:
  color: "#1565C0"
  image: assets/images/welcome.png
  android: true
  ios: true
