// lib/main.dart
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:firebase_core/firebase_core.dart';
import 'dart:io';
import 'dart:async';
import 'dart:ui';
import 'firebase_options.dart'; // Generated by FlutterFire CLI
import 'providers/request_provider.dart';
import 'providers/user_provider.dart';
import 'providers/provider_provider.dart'; // New provider state management for provider list flow
import 'providers/provider_dashboard_provider.dart'; // Provider dashboard state
import 'providers/appointment_provider.dart'; // Import new appointment provider
import 'providers/provider_data_provider.dart'; // Import new provider data provider
import 'providers/medical_questions_provider.dart'; // Import medical questions provider
import 'providers/theme_provider.dart'; // Import theme provider
import 'screens/main_screen.dart'; // Import the new MainScreen
import 'screens/splash_screen.dart'; // Import the new SplashScreen
import 'screens/error_details_screen.dart'; // Import the error details screen
import 'screens/provider/provider_dashboard_screen.dart'; // Import provider dashboard screen
import 'utils/debug_utils.dart'; // Import debug utilities
import 'package:flutter/foundation.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'theme.dart'; // Import our custom theme
import 'package:flutter_dotenv/flutter_dotenv.dart'; // Import dotenv
import 'package:voice_chat_core/voice_chat_core.dart'; // Import voice package
import 'package:audio_session/audio_session.dart'; // Import audio_session

// Global key for accessing the navigator state from anywhere
final GlobalKey<NavigatorState> navigatorKey = GlobalKey<NavigatorState>();

// Global error handlers
void _handlePlatformError(Object error, StackTrace stack) {
  _logError('Platform error', error, stack);
}

void _handleFlutterError(FlutterErrorDetails details) {
  _logError(
    'Flutter error',
    details.exception,
    details.stack ?? StackTrace.empty,
  );
}

Future<void> _handleZoneError(Object error, StackTrace stack) async {
  _logError('Zone error', error, stack);
}

void _logError(String type, Object error, StackTrace stack) {
  // Check for specific error types to provide better guidance
  bool isInheritedWidgetError =
      error.toString().contains('deactivated widget') ||
      error.toString().contains('Looking up a deactivated widget');

  // Log errors in debug mode
  if (kDebugMode) {
    debugPrint('$type: $error');
    if (isInheritedWidgetError) {
      debugPrint(
        'INHERITED WIDGET ERROR DETECTED: This is likely a Provider access after widget disposal',
      );
      debugPrint(
        'RECOMMENDATION: Store Provider references in variables during initState()',
      );
    }
    debugPrint('Stack trace: $stack');
  }

  // In production, you would send this to a remote logging service
  // like Firebase Crashlytics, Sentry, etc.

  // For deactivated widget errors, we should not show the UI error since it's a development issue
  if (!isInheritedWidgetError) {
    // Optionally show an error UI if the app is already running
    _showErrorUI(error.toString(), stack);
  }
}

void _showErrorUI(String errorMessage, [StackTrace? stack]) {
  // Only show UI if the app is running and we have access to the navigator
  if (navigatorKey.currentContext != null) {
    // Show a snackbar or dialog with the error
    final context = navigatorKey.currentContext!;

    // Only proceed if we can safely use this context
    if (!context.mounted) {
      debugPrint('Cannot show error UI: context is not mounted');
      return;
    }

    // Determine if this is a serious error that needs detailed reporting
    bool isSeriousError =
        errorMessage.contains("Firebase") ||
        errorMessage.contains("Exception") ||
        errorMessage.contains("Error") ||
        stack != null;

    // Use a future delayed to ensure this runs after the current build cycle
    Future.microtask(() {
      try {
        if (isSeriousError && context.mounted) {
          // For serious errors, show the detailed error screen
          Navigator.of(context).push(
            MaterialPageRoute(
              builder:
                  (context) => ErrorDetailsScreen(
                    errorMessage: errorMessage,
                    stackTrace: stack?.toString(),
                    timestamp: DateTime.now(),
                    onRetry: () {
                      Navigator.of(context).pop();
                      // Here you could add logic to retry the last operation if applicable
                    },
                  ),
            ),
          );
        } else if (context.mounted) {
          // For minor errors, just show a snackbar
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text(
                'An unexpected error occurred. Please try again later.',
              ),
              backgroundColor: Colors.red,
              duration: Duration(seconds: 5),
              action: SnackBarAction(
                label: 'Details',
                textColor: Colors.white,
                onPressed: () {
                  // Show error details screen when user requests more information
                  if (context.mounted) {
                    Navigator.of(context).push(
                      MaterialPageRoute(
                        builder:
                            (context) => ErrorDetailsScreen(
                              errorMessage: errorMessage,
                              stackTrace: stack?.toString(),
                              timestamp: DateTime.now(),
                            ),
                      ),
                    );
                  }
                },
              ),
            ),
          );
        }
      } catch (e) {
        // Last resort - if we can't show the error UI, just log it
        debugPrint('Failed to show error UI: $e');
      }
    });
  } else {
    debugPrint('Cannot show error UI: no valid context available');
  }
}

Future<void> main() async {
  // Install global error handlers
  PlatformDispatcher.instance.onError = (error, stack) {
    _handlePlatformError(error, stack);
    return true; // Indicates error was handled
  };
  FlutterError.onError = _handleFlutterError;

  // Run the app in a custom error zone
  runZonedGuarded<Future<void>>(() async {
    WidgetsFlutterBinding.ensureInitialized();

    // --- Configure Audio Session ---
    final session = await AudioSession.instance;
    await session.configure(
      AudioSessionConfiguration(
        // Correct way to combine options for iOS
        avAudioSessionCategory: AVAudioSessionCategory.playAndRecord,
        avAudioSessionCategoryOptions:
            AVAudioSessionCategoryOptions.allowBluetooth | // Use bitwise OR
            AVAudioSessionCategoryOptions.defaultToSpeaker,
        avAudioSessionMode: AVAudioSessionMode.voiceChat,
        // avAudioSessionSupportsInAppVoip: true, // This parameter doesn't exist
        avAudioSessionRouteSharingPolicy:
            AVAudioSessionRouteSharingPolicy.defaultPolicy,
        androidAudioAttributes: const AndroidAudioAttributes(
          // Keep const here
          contentType: AndroidAudioContentType.speech,
          usage:
              AndroidAudioUsage
                  .voiceCommunication, // Use voiceCommunication for AEC
        ),
        androidAudioFocusGainType: AndroidAudioFocusGainType.gain,
        // androidWillPauseWhenDucked: true, // Consider if needed
      ),
    );
    debugPrint("Audio session configured for playAndRecord / voiceChat");
    // ----------------------------------

    // Load environment variables from .env.local
    try {
      await dotenv.load(fileName: ".env.local");
      debugPrint(".env.local loaded successfully.");
    } catch (e) {
      debugPrint("Error loading .env.local file: $e");
      // Decide if you want to proceed without env vars or handle error
    }

    // Instantiate and initialize voice services
    final elevenLabsApiKey = dotenv.env['ELEVENLABS_API_KEY'];
    final openAiApiKey = dotenv.env['OPENAI_API_KEY'];

    // Add null/empty checks for API keys
    if (elevenLabsApiKey == null ||
        elevenLabsApiKey.isEmpty ||
        elevenLabsApiKey == 'replace_with_your_key') {
      debugPrint(
        'ELEVENLABS_API_KEY not found or is a placeholder in .env.local',
      );
      // Handle missing key error - maybe throw or use a default/disabled state
    }
    if (openAiApiKey == null ||
        openAiApiKey.isEmpty ||
        openAiApiKey == 'replace_with_your_key') {
      debugPrint('OPENAI_API_KEY not found or is a placeholder in .env.local');
      // Handle missing key error
    }

    // Only proceed if keys are valid (basic check)
    final elevenLabsService = ElevenLabsService(
      apiKey: elevenLabsApiKey ?? '',
      baseUrl: 'https://api.elevenlabs.io/v1',
      defaultVoiceId: 'pNInz6obpgDQGcFmaJgB',
      defaultModelId: 'eleven_flash_v2_5',
    );

    // SpeechService initialization needs the audio session instance
    final speechService = SpeechService(
      openAiApiKey: openAiApiKey ?? '',
      openAiChatUrl: 'https://api.openai.com/v1/chat/completions',
      elevenLabsService: elevenLabsService,
      audioSession: session, // Pass the configured session instance
    );

    try {
      await elevenLabsService.initialize();
      await speechService.initialize();
      debugPrint('Voice services initialized successfully.');
    } catch (e) {
      debugPrint("Error initializing voice services: $e");
      // Handle initialization error
    }

    // Print available debug commands in debug mode
    if (kDebugMode) {
      DebugUtils.printDebugCommands();
    }

    // Check for network connectivity to Firebase servers
    if (kDebugMode) {
      await checkFirebaseAvailability();
    }

    await initializeFirebaseWithRetry();

    // Sign out any existing user at app launch to prevent session conflicts
    await FirebaseAuth.instance.signOut();
    if (kDebugMode) {
      debugPrint('User signed out at app launch');
    }

    // Pass the initialized services to MyApp
    runApp(
      MyApp(
        speechService: speechService,
        elevenLabsService: elevenLabsService /*, audioSession: session*/,
      ),
    );
  }, _handleZoneError);
}

// Check if Firebase services are reachable
Future<void> checkFirebaseAvailability() async {
  try {
    debugPrint('Checking Firebase availability...');

    // Try to connect to common Firebase endpoints
    var firebaseHosts = [
      'firestore.googleapis.com',
      'firebase.googleapis.com',
      'firebaseio.com',
    ];

    Map<String, bool> reachabilityResults = {};

    for (var host in firebaseHosts) {
      try {
        final result = await InternetAddress.lookup(host);
        final isReachable =
            result.isNotEmpty && result[0].rawAddress.isNotEmpty;
        reachabilityResults[host] = isReachable;
        debugPrint('$host is ${isReachable ? 'reachable' : 'unreachable'}');
      } on SocketException {
        reachabilityResults[host] = false;
        debugPrint('Cannot reach $host');
      }
    }

    // Handle specific service unavailability
    if (!reachabilityResults['firebaseio.com']!) {
      debugPrint(
        'Warning: Realtime Database (firebaseio.com) is unreachable. Some features may be limited.',
      );
      // You could set a global flag here to indicate limited functionality
    }
  } catch (e) {
    debugPrint('Error checking Firebase availability: $e');
  }
}

Future<void> initializeFirebaseWithRetry() async {
  int maxRetries = 3;
  int retryCount = 0;
  bool initialized = false;

  while (!initialized && retryCount < maxRetries) {
    try {
      // Try to initialize Firebase with a timeout
      await Firebase.initializeApp(
        options: DefaultFirebaseOptions.currentPlatform,
      ).timeout(
        const Duration(seconds: 10),
        onTimeout: () {
          throw TimeoutException(
            'Firebase initialization timed out after 10 seconds',
          );
        },
      );

      initialized = true;

      if (kDebugMode) {
        debugPrint('Firebase initialized with production configuration');
      }
    } catch (e) {
      retryCount++;
      if (kDebugMode) {
        debugPrint('Failed to initialize Firebase: $e');

        // More detailed error information
        if (e is FirebaseException) {
          debugPrint('FirebaseException: ${e.code} - ${e.message}');
          debugPrint('Plugin: ${e.plugin}');
        } else if (e is SocketException) {
          debugPrint('SocketException: ${e.message}');
          debugPrint('Address: ${e.address?.address}, Port: ${e.port}');
        } else if (e is TimeoutException) {
          debugPrint('TimeoutException: Connection timed out');
        }

        debugPrint('Retry attempt $retryCount of $maxRetries');
      }

      if (retryCount < maxRetries) {
        await Future.delayed(Duration(seconds: 2 * retryCount));
      }
    }
  }

  if (!initialized) {
    if (kDebugMode) {
      debugPrint('Failed to initialize Firebase after $maxRetries attempts');
    }
    // You might want to show an error dialog or handle this case
  }
}

class MyApp extends StatelessWidget {
  // Accept the services as parameters
  final SpeechService speechService;
  final ElevenLabsService elevenLabsService;

  const MyApp({
    super.key,
    required this.speechService,
    required this.elevenLabsService,
  });

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        // Provide the existing service instances
        Provider<SpeechService>.value(value: speechService),
        Provider<ElevenLabsService>.value(value: elevenLabsService),

        // Existing providers
        ChangeNotifierProvider(create: (_) => RequestProvider()),
        ChangeNotifierProvider(create: (_) => UserProvider()),
        ChangeNotifierProvider(create: (_) => ProviderProvider()),
        ChangeNotifierProvider(create: (_) => ProviderDashboardProvider()),
        ChangeNotifierProvider(create: (_) => AppointmentProvider()),
        ChangeNotifierProvider(create: (_) => ProviderDataProvider()),
        ChangeNotifierProvider(create: (_) => MedicalQuestionsProvider()),
        ChangeNotifierProvider(create: (_) => ThemeProvider()),
      ],
      child: ProviderInitializer(
        child: Consumer<ThemeProvider>(
          builder: (context, themeProvider, child) {
            return MaterialApp(
              title: 'XUBER Health Prototype',
              debugShowCheckedModeBanner: false,
              theme: AppTheme.lightTheme,
              darkTheme: AppTheme.darkTheme,
              themeMode: themeProvider.themeMode,
              navigatorKey:
                  navigatorKey, // Add global navigator key for error handling
              // Use SplashScreen as the initial screen
              home: const SplashScreen(),
              // Define routes for navigation after login
              routes: {
                '/main': (context) => const MainScreen(),
                '/account':
                    (context) => const MainScreen(
                      initialTab: 3,
                    ), // Navigate to account tab (now at index 3)
                '/consults':
                    (context) => const MainScreen(
                      initialTab: 1,
                    ), // Navigate to consults tab
                '/activity':
                    (context) => const MainScreen(
                      initialTab: 2,
                    ), // Navigate to activity tab
                '/provider_dashboard':
                    (context) =>
                        const ProviderDashboardScreen(), // Add provider dashboard route
                // Add error details route for direct navigation
                '/error_details':
                    (context) => ErrorDetailsScreen(
                      errorMessage: 'Test error message',
                      stackTrace: 'Simulated stack trace for testing',
                      timestamp: DateTime.now(),
                    ),
                // Add other routes as needed
              },
            );
          },
        ),
      ),
    );
  }
}

// Modify AuthWrapper to navigate to MainScreen after successful login

// Add a provider initializer widget to initialize providers when the app starts
class ProviderInitializer extends StatefulWidget {
  final Widget child;

  const ProviderInitializer({super.key, required this.child});

  @override
  ProviderInitializerState createState() => ProviderInitializerState();
}

class ProviderInitializerState extends State<ProviderInitializer> {
  StreamSubscription<User?>? _authSubscription;

  @override
  void initState() {
    super.initState();
    _initializeProviders();
  }

  Future<void> _initializeProviders() async {
    // Initialize providers after user authentication
    _authSubscription = FirebaseAuth.instance.authStateChanges().listen((
      User? user,
    ) {
      if (!mounted) return; // Ensure widget is still mounted
      if (user != null) {
        // User is logged in, initialize providers
        final userProvider = Provider.of<UserProvider>(context, listen: false);
        final appointmentProvider = Provider.of<AppointmentProvider>(
          context,
          listen: false,
        );
        // Get medical questions provider reference
        final medicalQuestionsProvider = Provider.of<MedicalQuestionsProvider>(
          context,
          listen: false,
        );

        // Initialize user profile and appointments
        userProvider.initialize();
        appointmentProvider.initialize();

        // Don't navigate here - let the AuthWrapper handle navigation based on user role
        // This prevents overriding the provider dashboard navigation

        // Initialize medical questions provider
        Future.delayed(const Duration(milliseconds: 500), () {
          if (mounted) {
            // Initialize medical questions provider
            medicalQuestionsProvider.initialize();
          }
        });
      } else {
        // User signed out, clear data if needed (optional)
        Provider.of<UserProvider>(context, listen: false).clearUserData();
        // AuthWrapper will handle navigation back to sign-in
      }
    });
  }

  @override
  void dispose() {
    _authSubscription?.cancel(); // Cancel the listener
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return widget.child;
  }
}
