// lib/main.dart
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:firebase_core/firebase_core.dart';
import 'dart:io';
import 'dart:async';
import 'firebase_options.dart'; // Generated by FlutterFire CLI
import 'providers/request_provider.dart';
import 'providers/user_provider.dart';
import 'providers/provider_provider.dart'; // New provider state management for provider list flow
import 'providers/provider_dashboard_provider.dart'; // Provider dashboard state
import 'providers/appointment_provider.dart'; // Import new appointment provider
import 'providers/provider_data_provider.dart'; // Import new provider data provider
import 'screens/auth/auth_wrapper.dart';
import 'package:flutter/foundation.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'theme.dart'; // Import our custom theme

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Check for network connectivity to Firebase servers
  if (kDebugMode) {
    await checkFirebaseAvailability();
  }

  await initializeFirebaseWithRetry();

  // Sign out any existing user at app launch to prevent session conflicts
  await FirebaseAuth.instance.signOut();
  if (kDebugMode) {
    debugPrint('User signed out at app launch');
  }

  runApp(const MyApp());
}

// Check if Firebase services are reachable
Future<void> checkFirebaseAvailability() async {
  try {
    debugPrint('Checking Firebase availability...');

    // Try to connect to common Firebase endpoints
    var firebaseHosts = [
      'firestore.googleapis.com',
      'firebase.googleapis.com',
      'firebaseio.com',
    ];

    Map<String, bool> reachabilityResults = {};

    for (var host in firebaseHosts) {
      try {
        final result = await InternetAddress.lookup(host);
        final isReachable =
            result.isNotEmpty && result[0].rawAddress.isNotEmpty;
        reachabilityResults[host] = isReachable;
        debugPrint('$host is ${isReachable ? 'reachable' : 'unreachable'}');
      } on SocketException {
        reachabilityResults[host] = false;
        debugPrint('Cannot reach $host');
      }
    }

    // Handle specific service unavailability
    if (!reachabilityResults['firebaseio.com']!) {
      debugPrint(
        'Warning: Realtime Database (firebaseio.com) is unreachable. Some features may be limited.',
      );
      // You could set a global flag here to indicate limited functionality
    }
  } catch (e) {
    debugPrint('Error checking Firebase availability: $e');
  }
}

Future<void> initializeFirebaseWithRetry() async {
  int maxRetries = 3;
  int retryCount = 0;
  bool initialized = false;

  while (!initialized && retryCount < maxRetries) {
    try {
      // Try to initialize Firebase with a timeout
      await Firebase.initializeApp(
        options: DefaultFirebaseOptions.currentPlatform,
      ).timeout(
        const Duration(seconds: 10),
        onTimeout: () {
          throw TimeoutException(
            'Firebase initialization timed out after 10 seconds',
          );
        },
      );

      initialized = true;

      if (kDebugMode) {
        debugPrint('Firebase initialized with production configuration');
      }
    } catch (e) {
      retryCount++;
      if (kDebugMode) {
        debugPrint('Failed to initialize Firebase: $e');

        // More detailed error information
        if (e is FirebaseException) {
          debugPrint('FirebaseException: ${e.code} - ${e.message}');
          debugPrint('Plugin: ${e.plugin}');
        } else if (e is SocketException) {
          debugPrint('SocketException: ${e.message}');
          debugPrint('Address: ${e.address?.address}, Port: ${e.port}');
        } else if (e is TimeoutException) {
          debugPrint('TimeoutException: Connection timed out');
        }

        debugPrint('Retry attempt $retryCount of $maxRetries');
      }

      if (retryCount < maxRetries) {
        await Future.delayed(Duration(seconds: 2 * retryCount));
      }
    }
  }

  if (!initialized) {
    if (kDebugMode) {
      debugPrint('Failed to initialize Firebase after $maxRetries attempts');
    }
    // You might want to show an error dialog or handle this case
  }
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => RequestProvider()),
        ChangeNotifierProvider(create: (_) => UserProvider()),
        ChangeNotifierProvider(create: (_) => ProviderProvider()),
        ChangeNotifierProvider(create: (_) => ProviderDashboardProvider()),
        ChangeNotifierProvider(create: (_) => AppointmentProvider()),
        ChangeNotifierProvider(create: (_) => ProviderDataProvider()),
      ],
      child: ProviderInitializer(
        child: MaterialApp(
          title: 'Uber Health Prototype',
          debugShowCheckedModeBanner: false,
          theme: AppTheme.lightTheme, // Use our custom theme
          home: const AuthWrapper(),
        ),
      ),
    );
  }
}

// Add a provider initializer widget to initialize providers when the app starts
class ProviderInitializer extends StatefulWidget {
  final Widget child;

  const ProviderInitializer({super.key, required this.child});

  @override
  _ProviderInitializerState createState() => _ProviderInitializerState();
}

class _ProviderInitializerState extends State<ProviderInitializer> {
  @override
  void initState() {
    super.initState();
    _initializeProviders();
  }

  Future<void> _initializeProviders() async {
    // Initialize providers after user authentication
    FirebaseAuth.instance.authStateChanges().listen((User? user) {
      if (user != null) {
        // User is logged in, initialize providers
        final userProvider = Provider.of<UserProvider>(context, listen: false);
        final appointmentProvider = Provider.of<AppointmentProvider>(
          context,
          listen: false,
        );

        // Initialize user profile and appointments
        userProvider.initialize();
        appointmentProvider.initialize();
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return widget.child;
  }
}
